import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <button onClick={props.putValues}>押してみる</button>
      <main className={styles.main}>

        <div className={styles.grid}>
          {
            props.items.map(item => {
              return (
                <div className={`${styles.card} w-100`} key={item.id}>
                  {item.id}
                  <h2>{item.properties.Name.title[0].text?.content} &rarr;</h2>
                  <ul>
                    <li>
                      <Link href="/">
                        <a>{item.properties.Tags.multi_select[0]?.name}</a>
                      </Link>
                    </li>
                  </ul>
                  <p>Quantity : {item.properties.Quantity?.number}</p>
                  <p>Memo : {item.properties.Memo.rich_text[0]?.text?.content}</p>
                </div>
              )
            })
          }
        </div>
      </main>

      <footer className={styles.footer}>
        ©︎2022 mgk-design
      </footer>
    </div>
  )
}
